CREATE TABLE "User" ("id" TEXT NOT NULL, "openid" TEXT NOT NULL, "nickname" TEXT, "avatarUrl" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Trip" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "origin" TEXT NOT NULL, "destination" TEXT NOT NULL, "distanceKm" INTEGER, "days" INTEGER NOT NULL, "preferences" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Trip_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TripMember" ("tripId" TEXT NOT NULL, "userId" TEXT NOT NULL, "role" TEXT NOT NULL DEFAULT 'member', CONSTRAINT "TripMember_pkey" PRIMARY KEY ("tripId","userId"));
CREATE TABLE "TripDay" ("id" TEXT NOT NULL, "tripId" TEXT NOT NULL, "day" INTEGER NOT NULL, "location" TEXT NOT NULL, "events" JSONB NOT NULL, CONSTRAINT "TripDay_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TripStop" ("id" TEXT NOT NULL, "tripId" TEXT NOT NULL, "name" TEXT NOT NULL, "category" TEXT NOT NULL, "sort" INTEGER NOT NULL, "latitude" DOUBLE PRECISION, "longitude" DOUBLE PRECISION, "metadata" JSONB, CONSTRAINT "TripStop_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Favorite" ("userId" TEXT NOT NULL, "placeName" TEXT NOT NULL, "category" TEXT, "metadata" JSONB, CONSTRAINT "Favorite_pkey" PRIMARY KEY ("userId","placeName"));
CREATE TABLE "Invitation" ("id" TEXT NOT NULL, "tripId" TEXT NOT NULL, "inviterId" TEXT NOT NULL, "inviteeId" TEXT, "inviteeName" TEXT, "status" TEXT NOT NULL DEFAULT 'pending', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Invitation_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_openid_key" ON "User"("openid");
CREATE UNIQUE INDEX "TripDay_tripId_day_key" ON "TripDay"("tripId", "day");
ALTER TABLE "TripMember" ADD CONSTRAINT "TripMember_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TripMember" ADD CONSTRAINT "TripMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TripDay" ADD CONSTRAINT "TripDay_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TripStop" ADD CONSTRAINT "TripStop_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Favorite" ADD CONSTRAINT "Favorite_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Invitation" ADD CONSTRAINT "Invitation_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Invitation" ADD CONSTRAINT "Invitation_inviterId_fkey" FOREIGN KEY ("inviterId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Invitation" ADD CONSTRAINT "Invitation_inviteeId_fkey" FOREIGN KEY ("inviteeId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
